<?php

class PaisesTableSeeder extends Seeder {

	public function run()
	{
		$paises = array(
			array("country_id" => Str::lower("AF"), "country"  =>"Afganistán"),
			array("country_id" => Str::lower("AL"), "country"  =>"Albania"),
			array("country_id" => Str::lower("DE"), "country"  =>"Alemania"),
			array("country_id" => Str::lower("AD"), "country"  =>"Andorra"),
			array("country_id" => Str::lower("AO"), "country"  =>"Angola"),
			array("country_id" => Str::lower("AI"), "country"  =>"Anguilla"),
			array("country_id" => Str::lower("AQ"), "country"  =>"Antártida"),
			array("country_id" => Str::lower("AG"), "country"  =>"Antigua y Barbuda"),
			array("country_id" => Str::lower("AN"), "country"  =>"Antillas Holandesas"),
			array("country_id" => Str::lower("SA"), "country"  =>"Arabia Saud&iacute;"),
			array("country_id" => Str::lower("DZ"), "country"  =>"Argelia"),
			array("country_id" => Str::lower("AR"), "country"  =>"Argentina"),
			array("country_id" => Str::lower("AM"), "country"  =>"Armenia"),
			array("country_id" => Str::lower("AW"), "country"  =>"Aruba"),
			array("country_id" => Str::lower("AU"), "country"  =>"Australia"),
			array("country_id" => Str::lower("AT"), "country"  =>"Austria"),
			array("country_id" => Str::lower("AZ"), "country"  =>"Azerbaiyán"),
			array("country_id" => Str::lower("BS"), "country"  =>"Bahamas"),
			array("country_id" => Str::lower("BH"), "country"  =>"Bahrein"),
			array("country_id" => Str::lower("BD"), "country"  =>"Bangladesh"),
			array("country_id" => Str::lower("BB"), "country"  =>"Barbados"),
			array("country_id" => Str::lower("BE"), "country"  =>"Bélgica"),
			array("country_id" => Str::lower("BZ"), "country"  =>"Belice"),
			array("country_id" => Str::lower("BJ"), "country"  =>"Benin"),
			array("country_id" => Str::lower("BM"), "country"  =>"Bermudas"),
			array("country_id" => Str::lower("BY"), "country"  =>"Bielorrusia"),
			array("country_id" => Str::lower("MM"), "country"  =>"Birmania"),
			array("country_id" => Str::lower("BO"), "country"  =>"Bolivia"),
			array("country_id" => Str::lower("BA"), "country"  =>"Bosnia y Herzegovina"),
			array("country_id" => Str::lower("BW"), "country"  =>"Botswana"),
			array("country_id" => Str::lower("BR"), "country"  =>"Brasil"),
			array("country_id" => Str::lower("BN"), "country"  =>"Brunei"),
			array("country_id" => Str::lower("BG"), "country"  =>"Bulgaria"),
			array("country_id" => Str::lower("BF"), "country"  =>"Burkina Faso"),
			array("country_id" => Str::lower("BI"), "country"  =>"Burundi"),
			array("country_id" => Str::lower("BT"), "country"  =>"Bután"),
			array("country_id" => Str::lower("CV"), "country"  =>"Cabo Verde"),
			array("country_id" => Str::lower("KH"), "country"  =>"Camboya"),
			array("country_id" => Str::lower("CM"), "country"  =>"Camerún"),
			array("country_id" => Str::lower("CA"), "country"  =>"Canadá"),
			array("country_id" => Str::lower("TD"), "country"  =>"Chad"),
			array("country_id" => Str::lower("CL"), "country"  =>"Chile"),
			array("country_id" => Str::lower("CN"), "country"  =>"China"),
			array("country_id" => Str::lower("CY"), "country"  =>"Chipre"),
			array("country_id" => Str::lower("VA"), "country"  =>"Ciudad del Vaticano (Santa Sede)"),
			array("country_id" => Str::lower("CO"), "country"  =>"Colombia"),
			array("country_id" => Str::lower("KM"), "country"  =>"Comores"),
			array("country_id" => Str::lower("CG"), "country"  =>"Congo"),
			array("country_id" => Str::lower("CD"), "country"  =>"Congo, República Democrática del"),
			array("country_id" => Str::lower("KR"), "country"  =>"Corea"),
			array("country_id" => Str::lower("KP"), "country"  =>"Corea del Norte"),
			array("country_id" => Str::lower("CI"), "country"  =>"Costa de Marf&iacute;l"),
			array("country_id" => Str::lower("CR"), "country"  =>"Costa Rica"),
			array("country_id" => Str::lower("HR"), "country"  =>"Croacia (Hrvatska)"),
			array("country_id" => Str::lower("CU"), "country"  =>"Cuba"),
			array("country_id" => Str::lower("DK"), "country"  =>"Dinamarca"),
			array("country_id" => Str::lower("DJ"), "country"  =>"Djibouti"),
			array("country_id" => Str::lower("DM"), "country"  =>"Dominica"),
			array("country_id" => Str::lower("EC"), "country"  =>"Ecuador"),
			array("country_id" => Str::lower("EG"), "country"  =>"Egipto"),
			array("country_id" => Str::lower("SV"), "country"  =>"El Salvador"),
			array("country_id" => Str::lower("AE"), "country"  =>"Emiratos Árabes Unidos"),
			array("country_id" => Str::lower("ER"), "country"  =>"Eritrea"),
			array("country_id" => Str::lower("SI"), "country"  =>"Eslovenia"),
			array("country_id" => Str::lower("ES"), "country"  =>"Espa&ntilde;a"),
			array("country_id" => Str::lower("US"), "country"  =>"Estados Unidos"),
			array("country_id" => Str::lower("EE"), "country"  =>"Estonia"),
			array("country_id" => Str::lower("ET"), "country"  =>"Etiop&iacute;a"),
			array("country_id" => Str::lower("FJ"), "country"  =>"Fiji"),
			array("country_id" => Str::lower("PH"), "country"  =>"Filipinas"),
			array("country_id" => Str::lower("FI"), "country"  =>"Finlandia"),
			array("country_id" => Str::lower("FR"), "country"  =>"Francia"),
			array("country_id" => Str::lower("GA"), "country"  =>"Gab&oacute;n"),
			array("country_id" => Str::lower("GM"), "country"  =>"Gambia"),
			array("country_id" => Str::lower("GE"), "country"  =>"Georgia"),
			array("country_id" => Str::lower("GH"), "country"  =>"Ghana"),
			array("country_id" => Str::lower("GI"), "country"  =>"Gibraltar"),
			array("country_id" => Str::lower("GD"), "country"  =>"Granada"),
			array("country_id" => Str::lower("GR"), "country"  =>"Grecia"),
			array("country_id" => Str::lower("GL"), "country"  =>"Groenlandia"),
			array("country_id" => Str::lower("GP"), "country"  =>"Guadalupe"),
			array("country_id" => Str::lower("GU"), "country"  =>"Guam"),
			array("country_id" => Str::lower("GT"), "country"  =>"Guatemala"),
			array("country_id" => Str::lower("GY"), "country"  =>"Guayana"),
			array("country_id" => Str::lower("GF"), "country"  =>"Guayana Francesa"),
			array("country_id" => Str::lower("GN"), "country"  =>"Guinea"),
			array("country_id" => Str::lower("GQ"), "country"  =>"Guinea Ecuatorial"),
			array("country_id" => Str::lower("GW"), "country"  =>"Guinea-Bissau"),
			array("country_id" => Str::lower("HT"), "country"  =>"Hait&iacute;"),
			array("country_id" => Str::lower("HN"), "country"  =>"Honduras"),
			array("country_id" => Str::lower("HU"), "country"  =>"Hungr&iacute;a"),
			array("country_id" => Str::lower("IN"), "country"  =>"India"),
			array("country_id" => Str::lower("ID"), "country"  =>"Indonesia"),
			array("country_id" => Str::lower("IQ"), "country"  =>"Irak"),
			array("country_id" => Str::lower("IR"), "country"  =>"Irán"),
			array("country_id" => Str::lower("IE"), "country"  =>"Irlanda"),
			array("country_id" => Str::lower("BV"), "country"  =>"Isla Bouvet"),
			array("country_id" => Str::lower("CX"), "country"  =>"Isla de Christmas"),
			array("country_id" => Str::lower("IS"), "country"  =>"Islandia"),
			array("country_id" => Str::lower("KY"), "country"  =>"Islas Caimán"),
			array("country_id" => Str::lower("CK"), "country"  =>"Islas Cook"),
			array("country_id" => Str::lower("CC"), "country"  =>"Islas de Cocos o Keeling"),
			array("country_id" => Str::lower("FO"), "country"  =>"Islas Faroe"),
			array("country_id" => Str::lower("HM"), "country"  =>"Islas Heard y McDonald"),
			array("country_id" => Str::lower("FK"), "country"  =>"Islas Malvinas"),
			array("country_id" => Str::lower("MP"), "country"  =>"Islas Marianas del Norte"),
			array("country_id" => Str::lower("MH"), "country"  =>"Islas Marshall"),
			array("country_id" => Str::lower("UM"), "country"  =>"Islas menores de Estados Unidos"),
			array("country_id" => Str::lower("PW"), "country"  =>"Islas Palau"),
			array("country_id" => Str::lower("SB"), "country"  =>"Islas Salom&oacute;n"),
			array("country_id" => Str::lower("SJ"), "country"  =>"Islas Svalbard y Jan Mayen"),
			array("country_id" => Str::lower("TK"), "country"  =>"Islas Tokelau"),
			array("country_id" => Str::lower("TC"), "country"  =>"Islas Turks y Caicos"),
			array("country_id" => Str::lower("VI"), "country"  =>"Islas V&iacute;rgenes (EE.UU.)"),
			array("country_id" => Str::lower("VG"), "country"  =>"Islas V&iacute;rgenes (Reino Unido)"),
			array("country_id" => Str::lower("WF"), "country"  =>"Islas Wallis y Futuna"),
			array("country_id" => Str::lower("IL"), "country"  =>"Israel"),
			array("country_id" => Str::lower("IT"), "country"  =>"Italia"),
			array("country_id" => Str::lower("JM"), "country"  =>"Jamaica"),
			array("country_id" => Str::lower("JP"), "country"  =>"Jap&oacute;n"),
			array("country_id" => Str::lower("JO"), "country"  =>"Jordania"),
			array("country_id" => Str::lower("KZ"), "country"  =>"Kazajistán"),
			array("country_id" => Str::lower("KE"), "country"  =>"Kenia"),
			array("country_id" => Str::lower("KG"), "country"  =>"Kirguizistán"),
			array("country_id" => Str::lower("KI"), "country"  =>"Kiribati"),
			array("country_id" => Str::lower("KW"), "country"  =>"Kuwait"),
			array("country_id" => Str::lower("LA"), "country"  =>"Laos"),
			array("country_id" => Str::lower("LS"), "country"  =>"Lesotho"),
			array("country_id" => Str::lower("LV"), "country"  =>"Letonia"),
			array("country_id" => Str::lower("LB"), "country"  =>"L&iacute;bano"),
			array("country_id" => Str::lower("LR"), "country"  =>"Liberia"),
			array("country_id" => Str::lower("LY"), "country"  =>"Libia"),
			array("country_id" => Str::lower("LI"), "country"  =>"Liechtenstein"),
			array("country_id" => Str::lower("LT"), "country"  =>"Lituania"),
			array("country_id" => Str::lower("LU"), "country"  =>"Luxemburgo"),
			array("country_id" => Str::lower("MK"), "country"  =>"Macedonia, Ex-República Yugoslava de"),
			array("country_id" => Str::lower("MG"), "country"  =>"Madagascar"),
			array("country_id" => Str::lower("MY"), "country"  =>"Malasia"),
			array("country_id" => Str::lower("MW"), "country"  =>"Malawi"),
			array("country_id" => Str::lower("MV"), "country"  =>"Maldivas"),
			array("country_id" => Str::lower("ML"), "country"  =>"Mal&iacute;"),
			array("country_id" => Str::lower("MT"), "country"  =>"Malta"),
			array("country_id" => Str::lower("MA"), "country"  =>"Marruecos"),
			array("country_id" => Str::lower("MQ"), "country"  =>"Martinica"),
			array("country_id" => Str::lower("MU"), "country"  =>"Mauricio"),
			array("country_id" => Str::lower("MR"), "country"  =>"Mauritania"),
			array("country_id" => Str::lower("YT"), "country"  =>"Mayotte"),
			array("country_id" => Str::lower("MX"), "country"  =>"México"),
			array("country_id" => Str::lower("FM"), "country"  =>"Micronesia"),
			array("country_id" => Str::lower("MD"), "country"  =>"Moldavia"),
			array("country_id" => Str::lower("MC"), "country"  =>"M&oacute;naco"),
			array("country_id" => Str::lower("MN"), "country"  =>"Mongolia"),
			array("country_id" => Str::lower("MS"), "country"  =>"Montserrat"),
			array("country_id" => Str::lower("MZ"), "country"  =>"Mozambique"),
			array("country_id" => Str::lower("NA"), "country"  =>"Namibia"),
			array("country_id" => Str::lower("NR"), "country"  =>"Nauru"),
			array("country_id" => Str::lower("NP"), "country"  =>"Nepal"),
			array("country_id" => Str::lower("NI"), "country"  =>"Nicaragua"),
			array("country_id" => Str::lower("NE"), "country"  =>"N&iacute;ger"),
			array("country_id" => Str::lower("NG"), "country"  =>"Nigeria"),
			array("country_id" => Str::lower("NU"), "country"  =>"Niue"),
			array("country_id" => Str::lower("NF"), "country"  =>"Norfolk"),
			array("country_id" => Str::lower("NO"), "country"  =>"Noruega"),
			array("country_id" => Str::lower("NC"), "country"  =>"Nueva Caledonia"),
			array("country_id" => Str::lower("NZ"), "country"  =>"Nueva Zelanda"),
			array("country_id" => Str::lower("OM"), "country"  =>"Omán"),
			array("country_id" => Str::lower("NL"), "country"  =>"Pa&iacute;ses Bajos"),
			array("country_id" => Str::lower("PA"), "country"  =>"Panamá"),
			array("country_id" => Str::lower("PG"), "country"  =>"Papúa Nueva Guinea"),
			array("country_id" => Str::lower("PK"), "country"  =>"Paquistán"),
			array("country_id" => Str::lower("PY"), "country"  =>"Paraguay"),
			array("country_id" => Str::lower("PE"), "country"  =>"Perú"),
			array("country_id" => Str::lower("PN"), "country"  =>"Pitcairn"),
			array("country_id" => Str::lower("PF"), "country"  =>"Polinesia Francesa"),
			array("country_id" => Str::lower("PL"), "country"  =>"Polonia"),
			array("country_id" => Str::lower("PT"), "country"  =>"Portugal"),
			array("country_id" => Str::lower("PR"), "country"  =>"Puerto Rico"),
			array("country_id" => Str::lower("QA"), "country"  =>"Qatar"),
			array("country_id" => Str::lower("UK"), "country"  =>"Reino Unido"),
			array("country_id" => Str::lower("CF"), "country"  =>"República Centroafricana"),
			array("country_id" => Str::lower("CZ"), "country"  =>"República Checa"),
			array("country_id" => Str::lower("ZA"), "country"  =>"República de Sudáfrica"),
			array("country_id" => Str::lower("DO"), "country"  =>"República Dominicana"),
			array("country_id" => Str::lower("SK"), "country"  =>"República Eslovaca"),
			array("country_id" => Str::lower("RE"), "country"  =>"Reuni&oacute;n"),
			array("country_id" => Str::lower("RW"), "country"  =>"Ruanda"),
			array("country_id" => Str::lower("RO"), "country"  =>"Rumania"),
			array("country_id" => Str::lower("RU"), "country"  =>"Rusia"),
			array("country_id" => Str::lower("EH"), "country"  =>"Sahara Occidental"),
			array("country_id" => Str::lower("KN"), "country"  =>"Saint Kitts y Nevis"),
			array("country_id" => Str::lower("WS"), "country"  =>"Samoa"),
			array("country_id" => Str::lower("AS"), "country"  =>"Samoa Americana"),
			array("country_id" => Str::lower("SM"), "country"  =>"San Marino"),
			array("country_id" => Str::lower("VC"), "country"  =>"San Vicente y Granadinas"),
			array("country_id" => Str::lower("SH"), "country"  =>"Santa Helena"),
			array("country_id" => Str::lower("LC"), "country"  =>"Santa Luc&iacute;a"),
			array("country_id" => Str::lower("ST"), "country"  =>"Santo Tomé y Pr&iacute;ncipe"),
			array("country_id" => Str::lower("SN"), "country"  =>"Senegal"),
			array("country_id" => Str::lower("SC"), "country"  =>"Seychelles"),
			array("country_id" => Str::lower("SL"), "country"  =>"Sierra Leona"),
			array("country_id" => Str::lower("SG"), "country"  =>"Singapur"),
			array("country_id" => Str::lower("SY"), "country"  =>"Siria"),
			array("country_id" => Str::lower("SO"), "country"  =>"Somalia"),
			array("country_id" => Str::lower("LK"), "country"  =>"Sri Lanka"),
			array("country_id" => Str::lower("PM"), "country"  =>"St. Pierre y Miquelon"),
			array("country_id" => Str::lower("SZ"), "country"  =>"Suazilandia"),
			array("country_id" => Str::lower("SD"), "country"  =>"Sudán"),
			array("country_id" => Str::lower("SE"), "country"  =>"Suecia"),
			array("country_id" => Str::lower("CH"), "country"  =>"Suiza"),
			array("country_id" => Str::lower("SR"), "country"  =>"Surinam"),
			array("country_id" => Str::lower("TH"), "country"  =>"Tailandia"),
			array("country_id" => Str::lower("TW"), "country"  =>"Taiwán"),
			array("country_id" => Str::lower("TZ"), "country"  =>"Tanzania"),
			array("country_id" => Str::lower("TJ"), "country"  =>"Tayikistán"),
			array("country_id" => Str::lower("TF"), "country"  =>"Territorios franceses del Sur"),
			array("country_id" => Str::lower("TP"), "country"  =>"Timor Oriental"),
			array("country_id" => Str::lower("TG"), "country"  =>"Togo"),
			array("country_id" => Str::lower("TO"), "country"  =>"Tonga"),
			array("country_id" => Str::lower("TT"), "country"  =>"Trinidad y Tobago"),
			array("country_id" => Str::lower("TN"), "country"  =>"Túnez"),
			array("country_id" => Str::lower("TM"), "country"  =>"Turkmenistán"),
			array("country_id" => Str::lower("TR"), "country"  =>"Turqu&iacute;a"),
			array("country_id" => Str::lower("TV"), "country"  =>"Tuvalu"),
			array("country_id" => Str::lower("UA"), "country"  =>"Ucrania"),
			array("country_id" => Str::lower("UG"), "country"  =>"Uganda"),
			array("country_id" => Str::lower("UY"), "country"  =>"Uruguay"),
			array("country_id" => Str::lower("UZ"), "country"  =>"Uzbekistán"),
			array("country_id" => Str::lower("VU"), "country"  =>"Vanuatu"),
			array("country_id" => Str::lower("VE"), "country"  =>"Venezuela"),
			array("country_id" => Str::lower("VN"), "country"  =>"Vietnam"),
			array("country_id" => Str::lower("YE"), "country"  =>"Yemen"),
			array("country_id" => Str::lower("YU"), "country"  =>"Yugoslavia"),
			array("country_id" => Str::lower("ZM"), "country"  =>"Zambia"),
			array("country_id" => Str::lower("ZW"), "country"  =>"Zimbabue"),
		);

		// Uncomment the below to run the seeder
		DB::table('paises')->insert($paises);
	}

}
